name: Actions workflow
on:
    repository_dispatch:
      types: "test"

    pull_request:
      types:
        - "opened"
        - "reopened"

jobs:
    Github-Actions:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the github repository
          uses: actions/checkout@v3
        - run: echo " ${{ github.repository }}"
        - name: List files
          run: |
            ls ${{ github.workspace }}





